version: "3.8"
services:
  app-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - '5432:5432'
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
  myblog:
    build: ./myblog
    container_name: myblog_c
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - '3000:3000'
    volumes:
      - ./myblog:/app
      - /app/node_modules
    stdin_open: true
